name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:   ['ubuntu', 'macos', 'windows']
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Ruby-FFI before test
        run: |
          gem install ffi
          bundle install
      - run: bundle exec rake
